Importconfig
pingcap/tiup pull request #766
Opened 2020-09-09 03:38 UTC by yuzhibotao

### What problem does this PR solve? 
From ansible to tiup ，there is no configuration parameter for the import action.

### What is changed and how it works?

1. If the monitored_server is configured with deploy_dir and they are all the same, import deploy_dir into monitored_servers.
2.  Add information about global parameters and component parameters of TiDB PD TiKV .
After backing up the configuration files, parse the configuration files for each component, extract the same parameters into Server_Configs and put different parameters into the service's own Config.

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)
 
[old_meta.txt](https://github.com/pingcap/tiup/files/5192422/old_meta.txt)
[new_meta.txt](https://github.com/pingcap/tiup/files/5192428/new_meta.txt)

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

2020-09-09 03:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pingcap/tiup?pullRequest=766) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/tiup?pullRequest=766) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/tiup?pullRequest=766) it.</sub>

2020-09-10 07:23 UTC, lonng commented
@yuzhibotao Please add some tests and format your code.
@AstroProfundis PTAL

2020-09-10 10:10 UTC, AstroProfundis requested changes
You may use `go fmt` to format your code, and use `make check && make test` for basic code formatting and unit test checks.

2020-09-10 10:10 UTC, AstroProfundis commented on pkg/cluster/ansible/import.go
> +	prefixkey := ""
`prefixKey`

2020-09-10 10:10 UTC, AstroProfundis commented on pkg/cluster/ansible/import.go
> +	for i := 0 ; i < len(cls.Topology.TiDBServers); i++ {
Use `for i, srv := range cls.Topology.TiDBServers {...}` and then you can use `srv.ComponentName()` to replace `prefixkey`.

2020-09-10 10:10 UTC, AstroProfundis commented on pkg/cluster/ansible/import.go
> +	Configs :=  make(map[string]interface{})
no need to export the variable

2020-09-10 10:10 UTC, AstroProfundis commented on pkg/cluster/ansible/import.go
> +		// make Configs containts global Config variables
We have `Merge2Toml()` in `pkg/cluster/spec/server_config.go` that could be helpful for this purpose.

2020-09-10 10:10 UTC, AstroProfundis commented on pkg/cluster/ansible/import.go
> +            //make sure variables should be put in Server Configs or Global Configs
Could you explain more detail about what do this code block do and how it works?

2020-09-10 10:10 UTC, AstroProfundis commented on pkg/cluster/ansible/import.go
> +	for i := 0 ; i < len(cls.Topology.TiKVServers); i++ {
ditto

2020-09-10 10:10 UTC, AstroProfundis commented on pkg/cluster/spec/spec_manager.go
> +	// remove quotes
`Marshal()` converts the object to **valid** YAML bytes, so it's not a good idea to replace anything after it.

If the processing methods are all proper when building the `meta` object, it should be no invalid quote chars in the object.

2020-09-14 11:22 UTC, yuzhibotao commented on pkg/cluster/ansible/import.go
> +	if location_labels, ok := inventory.Groups["pd_servers"]; ok && len(location_labels.Vars["location_labels"]) > 0 {
Yes, but after importing, we will use edit-config to view the cluster topology and other detail information. The backup file cannot be displayed here, which is not friendly to dba.

2020-09-14 11:25 UTC, yuzhibotao commented on pkg/cluster/ansible/import.go
> +func CheckVarSame (key string, hosts map[string]*aini.Host) ([]string) {
Yes no need , I wanted to reuse this function for parameter comparison, but I gave up later.

2020-10-19 04:09 UTC, AstroProfundis reviewed
Rest LGTM

2020-10-19 04:09 UTC, AstroProfundis commented on pkg/cluster/ansible/import.go
> +// LoadConfig files to clusterMeta, just include tidbservers, tikvservers and pdservers
What about pump and drainer?

2020-10-19 04:09 UTC, AstroProfundis commented on pkg/cluster/ansible/import_test.go
> +	global, locals := diffConfigs([]map[string]interface{}{
should add cases for multi-level keys, e.g., `foo.bar: 1`.

2020-10-19 04:09 UTC, AstroProfundis commented on pkg/cluster/spec/tikv.go
> +		if sm, ok := serverLbs.(map[string]interface{}); ok {
`serverLbs` -> `serverLabels`

2020-10-19 04:09 UTC, AstroProfundis commented on pkg/set/string_set.go
> +type AnySet struct {
better split it to a dedicated file, e.g., `any_set.go`

2020-11-13 04:20 UTC, AstroProfundis approved these changes

2020-11-17 03:48 UTC, merged